### PR TITLE
added login page

### LINKED ISSUE #11: Design Log in page
Design a log in page which is user friendly and responsive.

If you open Facebook log in page in desktop mode then you can find how beautifully and easy to use they designed, you can take reference from there don't create same log in page like Facebook log in  use your unique ideas remember it is for a e-commerce website.

If you have any queries then you can ask here and if you willing to create a pull request then leave a comment like this (/attempt #11) and fork the repository and Find log_in.html on this repository to meke your changes use internal css in log_in.html file.

Please note that this is purely for learning purpose not promising any reward or bounty.

### PR DESCRIPTION
**Pull request by harshvyas-22**
Created responsive login page similar to facebook login page. closes #11

### CODE REVIEW

**Comment by harshvyas-22** [comment]
Capture

**Review by Sayantan73 — CHANGES_REQUESTED** [review]
Yeah this is great I like it 👍

Please use internal css means use all css properties in a single html file don't use extra style.css file so that it will be easy to maintain.

**Comment by harshvyas-22** [comment]
> Yeah this is great I like it 👍
> 
> Please use internal css means use all css properties in a single html file don't use extra style.css file so that it will be easy to maintain.

Yes done , you can check once

**Review by Sayantan73 — APPROVED** [review]
⭐

**Pull request merged**
